%% Get and sort the localizer data from the VMP files.
% Puts all the data into a matrix of params.NrLocalizerRuns (7) *
% params.NrTasks (7) * params.NrRepeats (4) * params.NrVoxels (106720)

for ParticipantNr = ParticipantsAnalyzed
    params.Participant = ParticipantNr;
    params.str_participant = ['P',num2str(ParticipantNr,'%02.f')]; % Makes sure the participant string number alwasy contains 2 digits.
    
    % Retrieve and sort the the t-values per task per run from the VMPs generated by BrainVoyager
    [LocalizerData,Filenames,LocalizerFilenames,TrialNames] = new22_OPTCLA2_Load_and_sort_vmp_data(params);
      % Apply whole-brain mask
      Mask = new22_OPTCLA2_ApplyMask(0,0,params.DataFolder,params.str_participant,params.AnalysisType); % T1 and t2 can be 0 because we're only using whole-brain (t1 and t2 are only needed for the NOI masked based on taskpair)
   
     
    % Store data in structure P
    P(ParticipantNr).Participant = ParticipantNr;
    P(ParticipantNr).Data.LocalizerData = LocalizerData; % runs x nr of tasks x nr of trials/repeats * nr of voxels
    P(ParticipantNr).LocalizerFilenames = LocalizerFilenames;
    P(ParticipantNr).TrialNames = TrialNames;
    P(ParticipantNr).Mask = Mask;
    
    clear LocalizerData;
    
end
